#ifndef AGMAGIC_DEFINED_COUNTER
#error	'Not define AGMAGIC_DEFINED_COUNTER'
#endif

#if		AGMAGIC_DEFINED_COUNTER==0
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	1
#elif	AGMAGIC_DEFINED_COUNTER==1
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	2
#elif	AGMAGIC_DEFINED_COUNTER==2
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	3
#elif	AGMAGIC_DEFINED_COUNTER==3
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	4
#elif	AGMAGIC_DEFINED_COUNTER==4
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	5
#elif	AGMAGIC_DEFINED_COUNTER==5
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	6
#elif	AGMAGIC_DEFINED_COUNTER==6
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	7
#elif	AGMAGIC_DEFINED_COUNTER==7
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	8
#elif	AGMAGIC_DEFINED_COUNTER==8
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	9
#elif	AGMAGIC_DEFINED_COUNTER==9
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	10
#elif	AGMAGIC_DEFINED_COUNTER==10
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	11
#elif	AGMAGIC_DEFINED_COUNTER==11
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	12
#elif	AGMAGIC_DEFINED_COUNTER==12
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	13
#elif	AGMAGIC_DEFINED_COUNTER==13
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	14
#elif	AGMAGIC_DEFINED_COUNTER==14
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	15
#elif	AGMAGIC_DEFINED_COUNTER==15
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	16
#elif	AGMAGIC_DEFINED_COUNTER==16
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	17
#elif	AGMAGIC_DEFINED_COUNTER==17
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	18
#elif	AGMAGIC_DEFINED_COUNTER==18
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	19
#elif	AGMAGIC_DEFINED_COUNTER==19
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	20
#elif	AGMAGIC_DEFINED_COUNTER==20
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	21
#elif	AGMAGIC_DEFINED_COUNTER==21
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	22
#elif	AGMAGIC_DEFINED_COUNTER==22
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	23
#elif	AGMAGIC_DEFINED_COUNTER==23
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	24
#elif	AGMAGIC_DEFINED_COUNTER==24
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	25
#elif	AGMAGIC_DEFINED_COUNTER==25
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	26
#elif	AGMAGIC_DEFINED_COUNTER==26
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	27
#elif	AGMAGIC_DEFINED_COUNTER==27
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	28
#elif	AGMAGIC_DEFINED_COUNTER==28
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	29
#elif	AGMAGIC_DEFINED_COUNTER==29
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	30
#elif	AGMAGIC_DEFINED_COUNTER==30
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	31
#elif	AGMAGIC_DEFINED_COUNTER==31
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	32
#elif	AGMAGIC_DEFINED_COUNTER==32
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	33



#elif	AGMAGIC_DEFINED_COUNTER==33
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	34
#elif	AGMAGIC_DEFINED_COUNTER==34
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	35
#elif	AGMAGIC_DEFINED_COUNTER==35
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	36
#elif	AGMAGIC_DEFINED_COUNTER==36
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	37
#elif	AGMAGIC_DEFINED_COUNTER==37
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	38
#elif	AGMAGIC_DEFINED_COUNTER==38
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	39
#elif	AGMAGIC_DEFINED_COUNTER==39
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	40
#elif	AGMAGIC_DEFINED_COUNTER==40
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	41
#elif	AGMAGIC_DEFINED_COUNTER==41
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	42
#elif	AGMAGIC_DEFINED_COUNTER==42
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	43
#elif	AGMAGIC_DEFINED_COUNTER==43
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	44
#elif	AGMAGIC_DEFINED_COUNTER==44
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	45
#elif	AGMAGIC_DEFINED_COUNTER==45
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	46
#elif	AGMAGIC_DEFINED_COUNTER==46
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	47
#elif	AGMAGIC_DEFINED_COUNTER==47
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	48
#elif	AGMAGIC_DEFINED_COUNTER==48
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	49
#elif	AGMAGIC_DEFINED_COUNTER==49
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	50
#elif	AGMAGIC_DEFINED_COUNTER==50
	#undef	AGMAGIC_DEFINED_COUNTER
	#define	AGMAGIC_DEFINED_COUNTER	51
#endif
