#if !defined(AGMAGIC_DB_H__84245235_A336_11D2_84B1_00C0DFF84685__INCLUDED_)
#define AGMAGIC_DB_H__84245235_A336_11D2_84B1_00C0DFF84685__INCLUDED_

#if AGMAGIC_OS_TYPE==AGMAGIC_WINDOWS_OS
	
#if AGMAGIC_SUPPORT_ADO
#ifndef IMPORTED_ADO_COMPONENT_ALREADY
#define IMPORTED_ADO_COMPONENT_ALREADY
#import "../lib/db/ado/msado20.tlb" \
   no_namespace rename("EOF", "EndOfFile")
#endif	//#ifndef IMPORTED_ADO_COMPONENT_ALREADY

#define AGMAGIC_SQLSERVER_ADO_PROVIDER		1
#define AGMAGIC_ACCESS_ADO_PROVIDER			2
#define AGMAGIC_ORACLE_ADO_PROVIDER			3
#define	AGMAGIC_DEFAULT_ADO_PROVIDER			AGMAGIC_ACCESS_ADO_PROVIDER

#else	//#if AGMAGIC_SUPPORT_ADO
#endif	//#if AGMAGIC_SUPPORT_ADO

#else	//#if AGMAGIC_OS_TYPE==AGMAGIC_WINDOWS_OS
#error _T("Implement not yet")
#endif	//#if AGMAGIC_OS_TYPE==AGMAGIC_WINDOWS_OS
#endif // !defined(AGMAGIC_DB_H__84245235_A336_11D2_84B1_00C0DFF84685__INCLUDED_)
