/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vn_edu_agu_portal_channels_CTimAnh */

#ifndef _Included_vn_edu_agu_portal_channels_CTimAnh
#define _Included_vn_edu_agu_portal_channels_CTimAnh
#ifdef __cplusplus
extern "C" {
#endif
#undef vn_edu_agu_portal_channels_CTimAnh_NORMAL_MODE
#define vn_edu_agu_portal_channels_CTimAnh_NORMAL_MODE 42L
#undef vn_edu_agu_portal_channels_CTimAnh_ABOUT_MODE
#define vn_edu_agu_portal_channels_CTimAnh_ABOUT_MODE 31337L
/*
 * Class:     vn_edu_agu_portal_channels_CTimAnh
 * Method:    searchImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vn_edu_agu_portal_channels_CTimAnh_searchImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
