//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DlgToolStatusBar.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_BOLD                         101
#define IDD_DLGTOOLSTATUSBAR_DIALOG     102
#define IDM_MAKECALL                    102
#define ID_DRAWING                      102
#define IDM_HANGUPCALL                  103
#define ID_STRIKEOUT                    103
#define IDM_ABOUT                       104
#define ID_HELP_ABOUT                   104
#define IDS_MYCOMPUTER                  105
#define IDS_HELP_BUTTON                 106
#define IDS_BOLD_BUTTON                 107
#define IDS_STRIKEOUT_BUTTON            108
#define IDM_LARGEICON                   108
#define IDS_DRAWING_BUTTON              109
#define IDS_PANE0                       110
#define IDM_LISTVIEW                    110
#define IDS_PANE1                       111
#define IDS_TITLE                       112
#define ID_TOOLBAR                      112
#define IDS_NEW                         113
#define IDM_NEW                         113
#define IDS_OPEN                        114
#define IDM_OPEN                        114
#define IDS_SAVE                        115
#define IDM_SAVE                        115
#define IDM_CUT                         116
#define IDS_CUT                         116
#define IDM_COPY                        117
#define IDS_COPY                        117
#define IDM_DELETE                      118
#define IDS_DELETE                      118
#define IDM_PASTE                       119
#define IDS_PASTE                       119
#define IDM_REPLACE                     120
#define IDS_REPLACE                     120
#define IDM_REDOW                       121
#define IDS_REDOW                       121
#define IDM_FIND                        122
#define IDS_FIND                        122
#define IDM_PRINT                       123
#define IDS_PRINT                       123
#define IDM_PRINTPRE                    124
#define IDS_PRINTPRE                    124
#define IDM_HELP                        125
#define IDS_HELP                        125
#define IDM_DETAILS                     126
#define IDS_DETAILS                     126
#define IDM_LARGEICONS                  127
#define IDS_LARGEICONS                  127
#define IDR_MAINFRAME                   128
#define IDM_LIST                        128
#define IDS_LIST                        128
#define IDR_MENU1                       129
#define IDM_SMALLICONS                  129
#define IDS_SMALLICONS                  129
#define IDM_SORTDATE                    130
#define IDS_SORTDATE                    130
#define IDM_SORTNAME                    131
#define IDS_SORTNAME                    131
#define IDB_BMP                         132
#define IDM_SORTTYPE                    132
#define IDS_SORTTYPE                    132
#define IDM_TOOLBAR                     133
#define IDM_SORTSIZE                    133
#define IDS_SORTSIZE                    133
#define IDM_VIEWHELP                    134
#define IDS_VIEWHELP                    134
#define IDI_MYCOMP                      135
#define ID_FLAT_TTOLBAR                 135
#define IDI_COMP                        136
#define ID_STANDARD_TOOLBAR             136
#define ID_VIEWSORT_TOOLBAR             137
#define IDI_ICON1                       138
#define IDI_MYCOMPUTER                  139
#define IDI_HELP                        141
#define IDI_DRAWING                     142
#define IDI_STRIKEOUT                   143
#define IDI_BOLD                        144
#define IDC_EDIT1                       1001
#define ID_FILE_EXIT                    32772
#define ID_BUTTON32773                  32773
#define ID_FLAT_TOOLBAR1                32777
#define ID_STANDARD_TOOLBAR1            32778
#define ID_VIEWSORT_TOOLBAR1            32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           142
#endif
#endif
